name: markdown-analysis-workflow

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
        paths:
        - '**/*.md'

jobs:
    markdown-analysis-job:
        runs-on: ubuntu-latest
        name: 'github actions: markdownlint'
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v3
        -   name: markdownlint
            uses: nosborn/github-action-markdown-cli@v1.1.1
            with:
                files: .
                config_file: ./.github/.markdownlint.yml
        -   name: markdown link check
            uses: gaurav-nelson/github-action-markdown-link-check@v1
            with:
                config-file: ./.github/.markdown-link-check.json
