name: Verify Markdown

on:
  pull_request:
    branches:
      - main
      - website/**
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Lint Markdown
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20
        with:
          globs: '**/*.md'
          separator: ","
          config: .github/config/.markdownlint-cli2.yaml

  verify-links:
    name: Verify links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@652f85bc57bb1e7d4327260decc10aa68f7694c3 # v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_level: any
          config_file: .github/config/linkspector.yaml
          show_stats: true

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@35a02bae020e6999c5c37fabaf447f2eb8822ca7 # v0
        with:
          config_path: .github/config/spellcheck.yml
          task_name: Markdown
